<?php use Phalcon\Tag as Tag ?>

<div class="span3">
    <ul class="nav nav-tabs nav-stacked">
        <li class="active">
            <a href="<?php echo $this->url->get('install/start'); ?>">Start Installation</a>
        </li>
        <li class="disabled">
            <a href="<?php echo $this->url->get('install/configuration'); ?>">Configuration</a>
        </li>
        <li class="disabled">
            <a href="<?php echo $this->url->get('install/finish'); ?>">You're All Set</a>
        </li>
    </ul>

    <br>
    <p>
        Having trouble installing Project Manager?
        <br>
        Check out our <a href="#">Installation Guide</a>
    </p>
</div>

<div class="span9">
    <h4 class="header">Welcome to Project Manager's Installation Wizard!</h4>

    <div class="gpl_license">
        <?php $this->partial('partials/gpl_license'); ?>
    </div>

    <form action="<?php echo $this->url->get('install/configuration'); ?>" method="post">
        <label class="checkbox">
            <input id="terms_condition_checkbox" type="checkbox" name="term_condition"> I agree to the above terms and conditions
        </label>

        <p class="pull-right">
            <button id="start_continue" type="submit" class="btn btn-primary">
                Continue
            </button>
        </p>
    </form>
</div>
