<?php use Phalcon\Tag as Tag ?>

<div class="span4">
    <h4 class="header">Tasks assigned to you</h4>
    <br>
    <?php if (count($tasksAssigned) == 0) { ?>
    <div class="align-center">
        <h5>No tasks are open for you!</h5>
    </div>
    <?php } else { ?>
        <div class="message-sidebar">
            <?php foreach($tasksAssigned AS $assignedTask) { ?>
                <a href="<?php echo $this->url->get('project/view/' . $assignedTask->getProject()->id . '/' . $assignedTask->id); ?>" class="message-preview new a-show-loader">
                    <abbr class="date pull-right"><?php echo date('D, j M Y H:i:s O', strtotime($assignedTask->created_at)); ?></abbr>
                    <h5>
                        <?php echo $assignedTask->getProject()->name; ?>
                        &nbsp;&nbsp;&nbsp;
                        <span>
                            <i class="icon-comments"></i>
                            <?php echo count($assignedTask->getComment()); ?>
                        </span>
                    </h5>
                    <h6><?php echo $assignedTask->title; ?></h6>
                    <?php if ($assignedTask->status == 0 && $assignedTask->hours > 0) { ?>
                        <div class="progress">
                            <?php
                                $timePercent = $assignedTask->getTimePercent();

                                if ($timePercent > 100) {
                                    $timeClass = 'bar-danger';
                                }
                                else if ($timePercent > 75) {
                                    $timeClass = 'bar-warning';
                                }
                                else {
                                    $timeClass = 'bar-success';
                                }
                            ?>
                            <div style="width: <?php echo $timePercent; ?>%;" class="bar <?php echo $timeClass; ?>"></div>
                        </div>
                    <?php } ?>
                </a>
            <?php } ?>
        </div>
    <?php } ?>
</div>

<div class="span8">
    <h4 class="header">Activity</h4>

    <div id="dashboardActivityBlock" class="activity">
        <?php if (count($activities) == 0) { ?>
            <div class="align-center">
                <h5>No activity!</h5>
            </div>
        <?php } else { ?>
            <?php foreach ($activities AS $activity) { ?>
                <a href="<?php echo $this->url->get($activity->getUrl()); ?>" class="activity-preview <?php echo ($activity->read == 0) ? 'new' : ''; ?> a-show-loader">
                    <div class="media">
                        <img class="media-object pull-left" src="<?php echo $this->url->get('profile/' . $activity->getUser()->getProfilePicture()); ?>">

                        <abbr class="date pull-right"><?php echo date('D, j M Y H:i:s O', strtotime($activity->created_at)); ?></abbr>

                        <div class="media-body">
                            <p class="media-heading span6">
                                <?php echo $activity->message; ?>
                            </p>
                        </div>
                    </div>
                </a>
            <?php } ?>
        <?php } ?>
    </div>
</div>