<?php use Phalcon\Tag as Tag ?>

<?php $project = $task->getProject(); ?>

<?php
	$notSubscribedUsers = null;

	foreach($project->getDevelopers() AS $_projectUser) {
		if (!$task->isSubscribed($_projectUser)) {
			$notSubscribedUsers[] = $_projectUser;
		}
	}
?>

<div class="row">
	<div class="span9">
		<div class="content_block well">
			<h4>
				<?php echo $task->title; ?>

				<a href="#editTask" role="button" class="btn btn-primary btn-small right" data-toggle="modal">Edit task</a>
			</h4>

			<div id="editTask" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
					<h3>Edit task</h3>
				</div>

				<?php echo Tag::form(array('task/savepost', 'class' => 'form-horizontal')); ?>
					<div class="modal-body">
						<div class="control-group">
							<label class="control-label" for="editTaskJobID">Job ID</label>
							<div class="controls">
								<input type="text" class="input-block-level" name="job_id" id="editTaskJobID" value="<?php echo $task->job_id; ?>">
							</div>
						</div>

						<div class="control-group">
							<label class="control-label" for="editTaskTitle">Title</label>
							<div class="controls">
								<input type="text" class="input-block-level" name="title" id="editTaskTitle" value="<?php echo $task->title; ?>">
							</div>
						</div>

						<div class="control-group">
							<label class="control-label" for="editTaskDescription">Description</label>
							<div class="controls">
								<textarea class="input-block-level" name="description" id="editTaskDescription" rows="6"><?php echo $task->description; ?></textarea>
							</div>
						</div>

						<div class="control-group">
							<label class="control-label" for="editTaskHours">Hours</label>
							<div class="controls">
								<input type="text" class="input-block-level" name="hours" id="editTaskHours" value="<?php echo ($task->getHours() > 0) ? $task->getHours() : ''; ?>">
							</div>
						</div>

						<div class="control-group">
							<label class="control-label" for="newTaskAssigned-<?php echo $project->id; ?>">Assigned to</label>
							<div class="controls">
								<select id="newTaskAssigned-<?php echo $project->id; ?>" name="assigned_to">
									<?php foreach($project->getDevelopers() AS $developer) { ?>
										<option value="<?php echo $developer->id; ?>" <?php echo ($task->assigned_to == $developer->id) ? 'selected="selected"' : ''; ?>><?php echo $developer->full_name; ?></option>
									<?php } ?>
								</select>
							</div>
						</div>

						<input type="hidden" value="task" name="controller">
						<input type="hidden" value="view/<?php echo $task->id; ?>" name="action">
						<input type="hidden" value="<?php echo $project->id; ?>" name="project_id">
						<input type="hidden" value="<?php echo $task->id; ?>" name="task_id">
					</div>

					<div class="modal-footer">
						<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
						<button class="btn btn-primary">Save changes</button>
					</div>
				</form>
			</div>

			<p>
				<span class="label label-info">Project : <?php echo $task->getProject()->name; ?></span>&nbsp;&nbsp;&nbsp;

				<?php if ($task->job_id) { ?>
					<span class="label label-info">Job ID : <?php echo $task->job_id; ?></span>&nbsp;&nbsp;&nbsp;
				<?php } ?>

				<span class="label label-info">Assigned to : <?php echo $task->getUser()->full_name; ?></span>&nbsp;&nbsp;&nbsp;
				<span class="label label-info">Hours : <?php echo $task->getHours(); ?></span>&nbsp;&nbsp;&nbsp;

				<?php if ($task->status == 0) { ?>
					<span class="label label-important">Open</span>
				<?php } else { ?>
					<span class="label label-success">Closed</span>
				<?php } ?>
			</p>

			<?php if ($task->description) { ?>
				<div class="task_description well">
					<?php echo Markdown($task->description); ?>
				</div>
			<?php } ?>
		</div>

		<hr>

		<?php $comments = $task->getComment(); ?>

		<?php if (count($comments) > 0) { ?>
		<div class="content_block well">
			<h5>Comments</h5>

			<table class="table table-bordered table-striped">
				<?php foreach($comments AS $comment) { ?>
					<tr id="comment-<?php echo $comment->id; ?>">
						<td>
							<p class="label label-inverse"><em><b><?php echo $comment->getUser()->full_name; ?></b> wrote on <?php echo $comment->created_at; ?></em></p>

							<div class="comment">
								<?php echo Markdown($comment->comment); ?>
							</div>

							<?php $uploads = $comment->getUploads(); ?>

							<?php if (count($uploads) > 0) { ?>
								<table role="presentation" class="table fileUploads table-bordered">
									<tbody data-toggle="modal-gallery" data-target="#modal-gallery">
										<?php foreach($uploads AS $upload) { ?>
											<?php $fileUrl = $this->url->get('uploads/' . $project->id . '/' . $upload->filename); ?>
											<tr class="fileUpload">
												<td class="preview">
													<?php if (in_array($upload->type, array('image/jpeg', 'image/png', 'image/gif'))) { ?>
														<a href="<?php echo $fileUrl; ?>" title="<?php echo $upload->filename; ?>" data-gallery="gallery" download="<?php echo $upload->filename; ?>">
															<img src="<?php echo $fileUrl; ?>" width="128" alt="<?php echo $upload->filename; ?>">
														</a>
													<?php } else { ?>
														<div class="<?php echo $upload->type; ?>"></div>
													<?php } ?>
												</td>
												<td class="content">
													<p>
														<a href="<?php echo $fileUrl; ?>" title="<?php echo $upload->filename; ?>" data-gallery="gallery" download="<?php echo $fileUrl; ?>">
															<?php echo $upload->filename; ?>
														</a>
													</p>
													<p>
														<?php echo $upload->size; ?>
													</p>
													<p>
														Uploaded by <?php echo $upload->getUser()->full_name; ?> at <?php echo $upload->uploaded_at; ?>
													</p>
												</td>
											</tr>
										<?php } ?>
									</tbody>
								</table>
							<?php } ?>
						</td>
					</tr>
				<?php } ?>
			</table>
		</div>

		<?php } ?>

		<div class="content_block well">
			<h5>Add new comment</h5>
			<?php echo Tag::form(array("task/addcomment", 'class' => 'form-horizontal', 'id' => 'fileupload', 'enctype' => 'multipart/form-data')); ?>
				<textarea class="input-block-level" rows="6" name="comment"></textarea>
				<input type="hidden" name="task_id" value="<?php echo $task->id; ?>">
				<input type="hidden" name="uuid" value="<?php echo $uuid; ?>">

				<br><br>

				<?php if ($currentUser->id == $task->assigned_to) { ?>
					<label class="checkbox">
						<input type="checkbox" name="task_complete" <?php echo ($task->status == 1) ? 'checked="checked"' : ''; ?>>
						Mark the task as complete.
					</label>
					<br />
				<?php } ?>

				<div class="row fileupload-buttonbar">
		            <div class="span7">
		                <!-- The fileinput-button span is used to style the file input field as button -->
		                <span class="btn btn-success fileinput-button">
		                    <i class="icon-plus icon-white"></i>
		                    <span>Add files...</span>
		                    <input type="file" name="files[]" multiple>
		                </span>
		            </div>
		        </div>
		        <table role="presentation" class="table fileUploads"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody></table>

		        <input type="submit" class="btn btn-primary" value="Add comment">
			</form>
		</div>
	</div>

	<div class="span3">
		<?php $this->partial("partials/attendance") ?>

		<?php if ($currentUser->id != $task->assigned_to) { ?>
			<?php if ($task->isSubscribed($currentUser)) { ?>
				<?php echo Tag::linkTo(array("task/unsubscribe/" . $task->id . "/" . $currentUser->id, "class" => "btn btn-danger btn-large input-block-level", "text" => "Unsubscribe")); ?>
			<?php } else { ?>
				<?php echo Tag::linkTo(array("task/subscribe/" . $task->id . "/" . $currentUser->id, "class" => "btn btn-primary btn-large input-block-level", "text" => "Subscribe")); ?>
			<?php } ?>
			<br />
		<?php } ?>

		<div class="sidebar_block well">
			<h4>Users</h4>

			<ol>
				<li><?php echo $task->getUser()->full_name; ?></li>

				<?php foreach($task->getTaskUser() AS $taskUser) { ?>
					<?php if ($taskUser->getUser()->id != $task->assigned_to) { ?>
						<li><?php echo $taskUser->getUser()->full_name; ?></li>
					<?php } ?>
				<?php } ?>

				<?php if (!is_null($notSubscribedUsers)) { ?>
					<?php foreach($notSubscribedUsers AS $notSubscribedUser) { ?>
						<li>
							<?php echo Tag::linkTo(array("task/subscribe/" . $task->id . "/" . $notSubscribedUser->id, "text" => $notSubscribedUser->full_name)); ?>
							<i class="icon-ok"></i>
					<?php } ?>
				<?php } ?>
			</ol>
		</div>

		<div class="sidebar_block well">
			<h4>Time Spent</h4>
			<?php foreach($task_user_time AS $_user_name => $_user_time) { ?>
				<p><?php echo $_user_name ?> : <?php echo $_user_time; ?></p>
			<?php } ?>

			<p><strong>Total Time : <?php echo $task_total_time; ?></strong></p>
		</div>
	</div>
</div>

<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade fileUpload">
		<td class="preview">
			<span class="fade"></span>
		</td>

		<td class="content">
			<p>
				{%=file.name%}
			</p>

			<p>
				{%=o.formatFileSize(file.size)%}
			</p>

			{% if (!file.error) { %}
				<div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="bar" style="width:0%;"></div></div>

				<p>
					<span class="start">
						<button class="btn btn-primary">
	                    	<i class="icon-upload icon-white"></i>
	                    	<span>Start</span>
	                	</button>
                	</span>&nbsp;&nbsp;
			{% } else { %}
				<p>
			{% } %}

				<span class="cancel">
					<button class="btn btn-warning">
		                <i class="icon-ban-circle icon-white"></i>
		                <span>Cancel</span>
		            </button>
		        </span>
	        </p>
		</td>
	</tr>
{% } %}
</script>

<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
	{% if (!file.error) { %}
		<tr class="template-download fade fileUpload">
			<td class="preview">
				{% if (file.thumbnail_url) { %}
					<a href="{%=file.url%}" title="{%=file.name%}" data-gallery="gallery" download="{%=file.name%}">
						<img src="{%=file.thumbnail_url%}" width="128" alt="{%=file.name%}">
					</a>
				{% } else { %}
					<div class="{%=file.type%}"></div>
				{% } %}
			</td>
			<td class="content">
				<p>
					<a href="{%=file.url%}" title="{%=file.name%}" data-gallery="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
				</p>
				<p>
					{%=o.formatFileSize(file.size)%}
				</p>
				<p>
					Uploaded by {%=file.uploaded_by%} at {%=file.uploaded_at%}
				</p>

				{% if (file.delete_url) { %}
					<p>
						<span class="delete">
							<button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
				                <i class="icon-trash icon-white"></i>
				                <span>Delete</span>
				            </button>
			            </span>
			        </p>
				{% } %}
			</td>
		</tr>
	{% } %}
{% } %}
</script>

<script type="text/javascript">
	$('#fileupload').fileupload({
		url: "<?php echo $this->url->get('files/post/' . $project->id . '/' . $task->id . '/'); ?>",
		prependFiles : true,
		previewMaxWidth: 128,
		autoUpload : true
    });
</script>

<div id="modal-gallery" class="modal modal-gallery hide fade" data-filter=":odd" tabindex="-1">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>
        <h3 class="modal-title"></h3>
    </div>
    <div class="modal-body"><div class="modal-image"></div></div>
    <div class="modal-footer">
        <a class="btn modal-download" target="_blank">
            <i class="icon-download"></i>
            <span>Download</span>
        </a>
        <a class="btn btn-success modal-play modal-slideshow" data-slideshow="5000">
            <i class="icon-play icon-white"></i>
            <span>Slideshow</span>
        </a>
        <a class="btn btn-info modal-prev">
            <i class="icon-arrow-left icon-white"></i>
            <span>Previous</span>
        </a>
        <a class="btn btn-primary modal-next">
            <span>Next</span>
            <i class="icon-arrow-right icon-white"></i>
        </a>
    </div>
</div>
