<?php use Phalcon\Tag as Tag ?>

<input type="hidden" id="fullCalendarEvenUrl" value="<?php echo $this->url->get('admin/getallholidaysajax'); ?>">

<div class="span4">
    <h4 class="header">Upcoming Holidays</h4>

    <div class="message-sidebar">
        <?php foreach ($allHolidays AS $holiday) { ?>
            <a href="javascript:void(0);" class="message-preview new">
                <h5><?php echo $holiday->name; ?></h5>
                <h6><?php echo date('l, jS F Y', strtotime($holiday->date)); ?></h6>
            </a>
        <?php } ?>
    </div>
</div>

<div class="span8">
    <div id="fullCalendar">
    </div>
</div>

<div id="newHoliday" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3>Add a new Leave</h3>
    </div>

    <form id="applyHolidayForm" class="form-horizontal" action="<?php echo $this->url->get('admin/applyholiday'); ?>">
        <div class="modal-body">
            <div class="control-group">
                <label class="control-label" for="newHolidayStartDate">Start Date</label>
                <div class="controls">
                    <input type="text" name="newHolidayStartDate" value="2013-02-10" data-date-format="yyyy-mm-dd" id="newHolidayStartDate" class="datepicker" readonly>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="newHolidayEndDate">End Date</label>
                <div class="controls">
                    <input type="text" name="newHolidayEndDate" value="2013-02-10" data-date-format="yyyy-mm-dd" id="newHolidayEndDate" class="datepicker" readonly>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="newHolidayName">Name</label>
                <div class="controls">
                    <input type="text" name="newHolidayName" id="newHolidayName" value="">
                </div>
            </div>
        </div>

        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
            <button id="applyHolidayFormSave" class="btn btn-primary">Save Holiday</button>
        </div>
    </form>
</div>

<div id="editHoliday" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3>Edit Holiday</h3>
    </div>

    <form id="editHolidayForm" class="form-horizontal" action="<?php echo $this->url->get('admin/editholiday'); ?>">
        <div class="modal-body">
            <div class="control-group">
                <label class="control-label" for="editHolidayDate">Date</label>
                <div class="controls">
                    <input type="text" name="editHolidayDate" value="2013-02-10" data-date-format="yyyy-mm-dd" id="editHolidayDate" class="datepicker" readonly>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="editHolidayName">Name</label>
                <div class="controls">
                    <input type="text" name="editHolidayName" id="editHolidayName" value="">
                </div>
            </div>

            <input type="hidden" id="editHolidayId" value="">
            <input type="hidden" id="editHolidayDeleteUrl" value="<?php echo $this->url->get('admin/deleteholiday'); ?>">
        </div>

        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
            <button id="editHolidayFormDelete" class="btn btn-danger">Delete Holiday</button>
            <button id="editHolidayFormSave" class="btn btn-primary">Save Holiday</button>
        </div>
    </form>
</div>
