<?php use Phalcon\Tag as Tag ?>

<div class="row">
	<div class="span3">
		<ul id="navbarSidebar" class="nav nav-list sidebarnav affix">
			<li>
				<a href="#general">
					<i class="icon-chevron-right right"></i>
					General Information
				</a>
			</li>

			<li>
				<a href="#developers">
					<i class="icon-chevron-right right"></i>
					Users
				</a>
			</li>

			<li>
				<a href="#holidays">
					<i class="icon-chevron-right right"></i>
					Holidays
				</a>
			</li>

			<li>
				<a href="#email">
					<i class="icon-chevron-right right"></i>
					Email settings
				</a>
			</li>
		</ul>
	</div>

	<div class="span9">
		<div id="general" class="content_block well well-large">
			<div class="block_title">
				<h4>General Information</h4>
			</div>

			<?php echo Tag::form(array('admin/configpost', 'class' => 'form-horizontal')); ?>
				<div class="control-group">
					<label class="control-label" for="siteName">Site name</label>
					<div class="controls">
						<input type="text" class="input-block-level" id="siteName" placeholder="Site name" name="config[core/name]" value="<?php echo Config::getValue('core/name'); ?>">
					</div>
				</div>

				<div class="control-group">
					<label class="control-label" for="siteEmail">Site email address</label>
					<div class="controls">
						<input type="text" class="input-block-level" id="siteEmail" placeholder="Site email address" name="config[core/email]" value="<?php echo Config::getValue('core/email'); ?>">
					</div>
				</div>

				<div class="control-group">
					<label class="control-label" for="siteBaseUrl">Base URL</label>
					<div class="controls">
						<input type="text" class="input-block-level" id="siteBaseUrl" placeholder="Base URL" name="config[core/baseUrl]" value="<?php echo Config::getValue('core/baseUrl'); ?>">
					</div>
				</div>

				<div class="control-group">
					<input type="hidden" value="admin" name="controller">
					<input type="hidden" value="index" name="action">
					<button class="btn btn-primary right" type="submit">Save</button>
				</div>
			</form>
		</div>

		<div id="developers" class="content_block well well-large">
			<div class="block_title">
				<h4 class="left">Users</h4>

				<a href="#newDeveloper" role="button" class="btn btn-primary right" data-toggle="modal">Add a user</a>

				<div id="newDeveloper" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
						<h3>Add a new user</h3>
					</div>

					<?php echo Tag::form(array('user/saveuser', 'class' => 'form-horizontal')); ?>
						<div class="modal-body">
							<div class="control-group">
								<label class="control-label" for="newDeveloperName">Full name</label>
								<div class="controls">
									<input type="text" class="input-block-level" id="newDeveloperName" placeholder="Full name" name="full_name">
								</div>
							</div>

							<div class="control-group">
								<label class="control-label" for="newDeveloperEmail">Email</label>
								<div class="controls">
									<input type="text" class="input-block-level" id="newDeveloperEmail" placeholder="Email address" name="email">
								</div>
							</div>

							<div class="control-group">
								<label class="control-label" for="newDeveloperPassword">Password</label>
								<div class="controls">
									<input type="password" class="input-block-level" id="newDeveloperPassword" placeholder="Password" name="password1">
								</div>
							</div>

							<div class="control-group">
								<label class="control-label" for="newDeveloperPassword2">Re-enter password</label>
								<div class="controls">
									<input type="password" class="input-block-level" id="newDeveloperPassword2" placeholder="Re-enter password" name="password2">
								</div>
							</div>

							<input type="hidden" value="admin" name="controller">
							<input type="hidden" value="index" name="action">
							<input type="hidden" value="2" name="role_id">
						</div>

						<div class="modal-footer">
							<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
							<button class="btn btn-primary">Save changes</button>
						</div>
					</form>
				</div>
			</div>

			<table class="table table-bordered table-striped">
				<thead>
					<tr>
						<th>Full Name</th>
						<th>Email</th>
						<th class="a-center">Actions</th>
					</tr>
				</thead>
				<tbody>
					<?php if (count($developers) > 0) { ?>
						<?php foreach ($developers AS $developer) { ?>
							<tr>
								<td><?php echo $developer->full_name; ?></td>
								<td><?php echo $developer->email; ?></td>
								<td class="a-center">
									<a href="#editDeveloper-<?php echo $developer->id; ?>" role="button" class="btn" data-toggle="modal">Edit</a>

									<div id="editDeveloper-<?php echo $developer->id; ?>" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
										<div class="modal-header">
											<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
											<h3>Edit developer</h3>
										</div>

										<?php echo Tag::form(array('user/saveuser/' . $developer->id, 'class' => 'form-horizontal')); ?>
											<div class="modal-body">
												<div class="control-group">
													<label class="control-label" for="editDeveloperName-<?php echo $developer->id; ?>">Full name</label>
													<div class="controls">
														<input type="text" class="input-block-level" id="editDeveloperName-<?php echo $developer->id; ?>" placeholder="Full name" name="full_name" value="<?php echo $developer->full_name; ?>">
													</div>
												</div>

												<div class="control-group">
													<label class="control-label" for="editDeveloperEmail-<?php echo $developer->id; ?>">Email</label>
													<div class="controls">
														<input type="text" class="input-block-level" id="editDeveloperEmail-<?php echo $developer->id; ?>" placeholder="Email address" name="email" value="<?php echo $developer->email; ?>">
													</div>
												</div>

												<div class="control-group">
													<label class="control-label" for="editDeveloperPassword-<?php echo $developer->id; ?>">Password</label>
													<div class="controls">
														<input type="password" class="input-block-level" id="editDeveloperPassword-<?php echo $developer->id; ?>" placeholder="Password" name="password1">
													</div>
												</div>

												<div class="control-group">
													<label class="control-label" for="editDeveloperPassword2-<?php echo $developer->id; ?>">Re-enter password</label>
													<div class="controls">
														<input type="password" class="input-block-level" id="editDeveloperPassword2-<?php echo $developer->id; ?>" placeholder="Re-enter password" name="password2">
													</div>
												</div>

												<input type="hidden" value="admin" name="controller">
												<input type="hidden" value="index" name="action">
												<input type="hidden" value="2" name="role_id">
												<input type="hidden" value="<?php echo $developer->id; ?>" name="id">
											</div>

											<div class="modal-footer">
												<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
												<button class="btn btn-primary">Save changes</button>
											</div>
										</form>
									</div>
								</td>
							</tr>
						<?php } ?>
					<?php } else { ?>
						<tr>
							<td colspan="3" class="empty-table">
								No users! Why not add some?
							</td>
						</tr>
					<?php } ?>
				</tbody>
			</table>
		</div>




		<div id="holidays" class="content_block well well-large">
			<div class="block_title">
				<h4 class="left">Holidays</h4>

				<a href="#newHoliday" role="button" class="btn btn-primary right" data-toggle="modal" data-keyboard="false">Add a holiday</a>

				<div id="newHoliday" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
						<h3>Add a new holiday</h3>
					</div>

					<?php echo Tag::form(array('holiday/savepost', 'class' => 'form-horizontal')); ?>
						<div class="modal-body">
							<div class="control-group">
								<label class="control-label" for="newHolidayName">Name of the holiday</label>
								<div class="controls">
									<input type="text" class="input-block-level" id="newHolidayName" placeholder="Holiday Name" name="name">
								</div>
							</div>

							<div class="control-group">
								<label class="control-label" for="newHolidayDate">Date</label>
								<div class="controls">
									<input type="text" class="input-block-level jdpicker" id="newHolidayDate" placeholder="Date" name="date">
								</div>
							</div>

							<input type="hidden" value="admin" name="controller">
							<input type="hidden" value="index" name="action">
						</div>

						<div class="modal-footer">
							<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
							<button class="btn btn-primary">Save changes</button>
						</div>
					</form>
				</div>
			</div>

			<table class="table table-bordered table-striped">
				<thead>
					<tr>
						<th>Date</th>
						<th>Name</th>
						<th class="a-center">Actions</th>
					</tr>
				</thead>
				<tbody>
					<?php if (count($holidays) > 0) { ?>
						<?php foreach ($holidays AS $holiday) { ?>
							<tr>
								<td><?php echo $holiday->date; ?></td>
								<td><?php echo $holiday->name; ?></td>
								<td class="a-center">
									<a href="#editHoliday-<?php echo $holiday->id; ?>" role="button" class="btn" data-toggle="modal" data-keyboard="false">Edit</a>

									<div id="editHoliday-<?php echo $holiday->id; ?>" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
										<div class="modal-header">
											<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
											<h3>Edit holiday</h3>
										</div>

										<?php echo Tag::form(array('holiday/savepost/' . $holiday->id, 'class' => 'form-horizontal')); ?>
											<div class="modal-body">
												<div class="control-group">
													<label class="control-label" for="editHolidayName-<?php echo $holiday->id; ?>">Name of the holiday</label>
													<div class="controls">
														<input type="text" class="input-block-level" id="editHolidayName-<?php echo $holiday->id; ?>" placeholder="Holiday name" name="name" value="<?php echo $holiday->name; ?>">
													</div>
												</div>

												<div class="control-group">
													<label class="control-label" for="editHolidayDate-<?php echo $holiday->id; ?>">Date</label>
													<div class="controls">
														<input type="text" class="input-block-level jdpicker" id="editHolidayDate-<?php echo $holiday->id; ?>" placeholder="Date" name="date" value="<?php echo $holiday->date; ?>">
													</div>
												</div>

												<input type="hidden" value="admin" name="controller">
												<input type="hidden" value="index" name="action">
												<input type="hidden" value="<?php echo $holiday->id; ?>" name="holiday_id">
											</div>

											<div class="modal-footer">
												<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
												<button class="btn btn-primary">Save changes</button>
											</div>
										</form>
									</div>
								</td>
							</tr>
						<?php } ?>
					<?php } else { ?>
						<tr>
							<td colspan="3" class="empty-table">
								No holidays! Why not add some?
							</td>
						</tr>
					<?php } ?>
				</tbody>
			</table>
		</div>

		<div id="email" class="content_block well well-large">
			<div class="block_title">
				<h4>Email settings</h4>
			</div>

			<?php echo Tag::form(array('admin/configpost', 'class' => 'form-horizontal')); ?>
				<div class="control-group">
					<label class="control-label" for="emailHost">Host</label>
					<div class="controls">
						<input type="text" class="input-block-level" id="emailHost" placeholder="Email hostname" name="config[email/host]" value="<?php echo Config::getValue('email/host'); ?>">
					</div>
				</div>

				<div class="control-group">
					<label class="control-label" for="emailUsername">Username</label>
					<div class="controls">
						<input type="text" class="input-block-level" id="emailUsername" placeholder="Email username" name="config[email/username]" value="<?php echo Config::getValue('email/username'); ?>">
					</div>
				</div>

				<div class="control-group">
					<label class="control-label" for="emailPassword">Password</label>
					<div class="controls">
						<input type="password" class="input-block-level" id="emailPassword" placeholder="Email password" name="config[email/password]" value="<?php echo Config::getValue('email/password'); ?>">
					</div>
				</div>

				<div class="control-group">
					<label class="control-label" for="emailPort">Port</label>
					<div class="controls">
						<input type="text" id="emailPort" placeholder="Email server port number" name="config[email/port]" value="<?php echo Config::getValue('email/port'); ?>">
					</div>
				</div>

				<div class="control-group">
					<label class="control-label" for="emailSSL">SSL</label>
					<div class="controls">
						<select id="emailSSL" class="input-small" name="config[email/ssl]">
							<option value="0" <?php echo (Config::getValue('email/ssl') == 0) ? 'selected="selected"' : ''; ?>>No</option>
							<option value="1" <?php echo (Config::getValue('email/ssl') == 1) ? 'selected="selected"' : ''; ?>>Yes</option>
						</select>
					</div>
				</div>

				<div class="control-group">
					<input type="hidden" value="admin" name="controller">
					<input type="hidden" value="index" name="action">
					<button class="btn btn-primary right" type="submit">Save</button>
				</div>
			</form>
		</div>
	</div>
</div>
