<?php use Phalcon\Tag as Tag ?>

<div class="span4">
    <ul class="nav nav-tabs nav-stacked">
        <li>
            <a href="#adminManageGeneralSettings">
                General Settings
            </a>
        </li>
        <li>
            <a href="#adminManageEmailSettings">
                Email Settings
            </a>
        </li>
        <li>
            <a href="#adminManageAttendanceSettings">
                Attendance Settings
            </a>
        </li>
    </ul>
</div>

<div class="span8">
    <h4 id="adminManageGeneralSettings" class="header">General Settings</h4>
    <form action="<?php echo $this->url->get('admin/savegeneral'); ?>" method="post" class="form-horizontal">
        <div class="control-group">
            <label class="control-label" for="adminManageCoreName">Application Name</label>
            <div class="controls">
                <input type="text" name="core_name" id="adminManageCoreName" value="<?php echo $core_name; ?>" autocomplete="off">
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="adminManageCoreEmail">Application Email</label>
            <div class="controls">
                <input type="email" name="core_email" id="adminManageCoreEmail" value="<?php echo $core_email; ?>" autocomplete="off">
            </div>
        </div>

        <input type="hidden" name="controller" value="<?php echo $controller; ?>">
        <input type="hidden" name="action" value="<?php echo $action . '/' . $url_params; ?>">

        <div class="control-group">
            <div class="controls">
                <button type="submit" class="btn">Save</button>
            </div>
        </div>
    </form>

    <br>

    <h4 id="adminManageEmailSettings" class="header">Email Settings</h4>
    <form action="<?php echo $this->url->get('admin/saveemail'); ?>" method="post" class="form-horizontal">
        <div class="control-group">
            <label class="control-label" for="adminManageEmailHost">Host</label>
            <div class="controls">
                <input type="text" name="email_host" id="adminManageEmailHost" value="<?php echo $email_host; ?>" autocomplete="off">
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="adminManageEmailUsername">Username</label>
            <div class="controls">
                <input type="text" name="email_username" id="adminManageEmailUsername" value="<?php echo $email_username; ?>" autocomplete="off">
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="adminManageEmailPassword">Password</label>
            <div class="controls">
                <input type="password" name="email_password" id="adminManageEmailPassword" value="<?php echo $email_password; ?>" autocomplete="off">
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="adminManageEmailPort">Port</label>
            <div class="controls">
                <input type="number" name="email_port" id="adminManageEmailPort" value="<?php echo $email_port; ?>" autocomplete="off">
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="adminManageEmailSsl">SSL</label>
            <div class="controls">
                <select name="email_ssl" id="adminManageEmailSsl" autocomplete="off">
                    <option value="0" <?php echo ($email_ssl == '0') ? 'selected="selected"' : ''; ?>>No</option>
                    <option value="1" <?php echo ($email_ssl == '1') ? 'selected="selected"' : ''; ?>>Yes</option>
                </select>
            </div>
        </div>

        <input type="hidden" name="controller" value="<?php echo $controller; ?>">
        <input type="hidden" name="action" value="<?php echo $action . '/' . $url_params; ?>">

        <div class="control-group">
            <div class="controls">
                <button type="submit" class="btn">Save</button>
            </div>
        </div>
    </form>

    <br>

    <h4 id="adminManageAttendanceSettings" class="header">Attendance Settings</h4>
    <form action="<?php echo $this->url->get('admin/saveattendance'); ?>" method="post" class="form-horizontal">
        <div class="control-group">
            <label class="control-label" for="adminManageAttendanceDaysTargetTime">Days Target Hours</label>
            <div class="controls">
                <input type="number" name="attendance_days_target_time" id="adminManageAttendanceDaysTargetTime" value="<?php echo $attendance_days_target_time; ?>" autocomplete="off">
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="adminManageAttendanceLeavesPerMonth">Leaves Per Month</label>
            <div class="controls">
                <input type="number" name="attendance_leaves_per_month" id="adminManageAttendanceLeavesPerMonth" value="<?php echo $attendance_leaves_per_month; ?>" autocomplete="off">
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="adminManageAttendanceLeavesPerQuarter">Leaves Per Quarter</label>
            <div class="controls">
                <input type="number" name="attendance_leaves_per_quarter" id="adminManageAttendanceLeavesPerQuarter" value="<?php echo $attendance_leaves_per_quarter; ?>" autocomplete="off">
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="adminManageAttendanceLeavesPerYear">Leaves Per Year</label>
            <div class="controls">
                <input type="number" name="attendance_leaves_per_year" id="adminManageAttendanceLeavesPerYear" value="<?php echo $attendance_leaves_per_year; ?>" autocomplete="off">
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="adminManageAttendanceLeavesMethod">Leaves Method</label>
            <div class="controls">
                <select name="attendance_leaves_method" id="adminManageAttendanceLeavesMethod" autocomplete="off">
                    <option value="month" <?php echo ($attendance_leaves_method == 'month') ? 'selected="selected"' : ''; ?>>
                        Month
                    </option>
                    <option value="quarter" <?php echo ($attendance_leaves_method == 'quarter') ? 'selected="selected"' : ''; ?>>
                        Quarter
                    </option>
                    <option value="year" <?php echo ($attendance_leaves_method == 'year') ? 'selected="selected"' : ''; ?>>
                        Year
                    </option>
                </select>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="adminManageAttendanceLeavesCarries">Leaves Carries</label>
            <div class="controls">
                <select name="attendance_leaves_carries" id="adminManageAttendanceLeavesCarries" autocomplete="off">
                    <option value="0" <?php echo ($attendance_leaves_carries == '0') ? 'selected="selected"' : ''; ?>>No</option>
                    <option value="1" <?php echo ($attendance_leaves_carries == '1') ? 'selected="selected"' : ''; ?>>Yes</option>
                </select>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="adminManageAttendanceWeekoffs">Weekoff's</label>
            <div class="controls">
                <select name="attendance_weekoffs[]" id="adminManageAttendanceWeekoffs" autocomplete="off" multiple>
                    <option value="7" <?php echo (in_array('7', $attendance_weekoffs)) ? 'selected="selected"' : ''; ?>>
                        Sunday
                    </option>
                    <option value="1" <?php echo (in_array('1', $attendance_weekoffs)) ? 'selected="selected"' : ''; ?>>
                        Monday
                    </option>
                    <option value="2" <?php echo (in_array('2', $attendance_weekoffs)) ? 'selected="selected"' : ''; ?>>
                        Tuesday
                    </option>
                    <option value="3" <?php echo (in_array('3', $attendance_weekoffs)) ? 'selected="selected"' : ''; ?>>
                        Wednesday
                    </option>
                    <option value="4" <?php echo (in_array('4', $attendance_weekoffs)) ? 'selected="selected"' : ''; ?>>
                        Thursday
                    </option>
                    <option value="5" <?php echo (in_array('5', $attendance_weekoffs)) ? 'selected="selected"' : ''; ?>>
                        Friday
                    </option>
                    <option value="6" <?php echo (in_array('6', $attendance_weekoffs)) ? 'selected="selected"' : ''; ?>>
                        Saturday
                    </option>
                </select>
            </div>
        </div>

        <input type="hidden" name="controller" value="<?php echo $controller; ?>">
        <input type="hidden" name="action" value="<?php echo $action . '/' . $url_params; ?>">

        <div class="control-group">
            <div class="controls">
                <button type="submit" class="btn">Save</button>
            </div>
        </div>
    </form>
</div>
