<?php use Phalcon\Tag as Tag ?>

<input type="hidden" id="fullCalendarEvenUrl" value="<?php echo $this->url->get('admin/getallleavesajax'); ?>">

<div class="span4">
    <h4 class="header">Users</h4>

    <div class="message-sidebar">
        <?php foreach ($allUsers AS $user) { ?>
            <a href="javascript:void(0);" class="message-preview new">
                <h5><?php echo $user->full_name; ?></h5>
                <h6>Leaves Remaining : <?php echo $user->getAvailLeavesCount(); ?></h6>
                <h6>Leaves Pending for Approval : <?php echo $user->getPendingLeavesCount(); ?></h6>
            </a>
        <?php } ?>
    </div>
</div>

<div class="span8">
    <div id="fullCalendar">
    </div>
</div>

<div id="newLeave" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3>Add a new Leave</h3>
    </div>

    <form id="applyLeaveForm" class="form-horizontal" action="<?php echo $this->url->get('admin/applyleave'); ?>">
        <div class="modal-body">
            <div class="control-group">
                <label class="control-label" for="leavesUser">User</label>
                <div class="controls">
                    <select id="leavesUser" name="leavesUser" required="required">
                        <option value="0" selected="selected">-- Please Select --</option>
                        <?php foreach ($allUsers AS $user) { ?>
                            <option value="<?php echo $user->id; ?>">
                                <?php echo $user->full_name; ?>
                            </option>
                        <?php } ?>
                    </select>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="leavesFrom">From</label>
                <div class="controls">
                    <input type="text" name="leavesFrom" value="2013-02-10" data-date-format="yyyy-mm-dd" id="leavesFrom" class="datepicker" readonly>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="leavesTo">To</label>
                <div class="controls">
                    <input type="text" name="leavesTo" value="" data-date-format="yyyy-mm-dd" id="leavesTo" class="datepicker" readonly>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="leavesReason">Reason</label>
                <div class="controls">
                    <textarea id="leavesReason" name="leavesReason" rows="4"></textarea>
                </div>
            </div>
        </div>

        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
            <button id="applyLeaveFormSave" class="btn btn-primary">Save Leave</button>
        </div>
    </form>
</div>

<div id="editLeave" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3>Approve or Decline</h3>
    </div>

    <form id="editLeaveForm" class="form-horizontal" action="<?php echo $this->url->get('admin/approveleave'); ?>">
        <input type="hidden" id="editLeaveId" name="leaveId" value="">
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
            <button id="editLeaveFormDecline" class="btn btn-danger">Decline Leave</button>
            <button id="editLeaveFormApprove" class="btn btn-primary">Approve Leave</button>
        </div>
    </form>
</div>
