<?php use Phalcon\Tag as Tag ?>

<div class="sidebar_block well">
	<?php echo Tag::form(array('attendance/savepost')); ?>
		<input type="hidden" name="user_id" value="<?php echo $currentUser->id; ?>">
		<input type="hidden" name="controller" value="<?php echo $this->view->getControllerName(); ?>">
		<input type="hidden" name="action" value="<?php echo $this->view->getActionName(); ?>">

		<?php if (!is_null($attendance)) { ?>
			<input type="hidden" name="attendance_id" value="<?php echo $attendance->id; ?>">
			<button class="btn btn-inverse btn-large sidebar_btn" type="submit">End Time</button>
		<?php } else { ?>
			<button class="btn btn-inverse btn-large sidebar_btn" type="submit">Start Time</button>
		<?php } ?>
	</form>

	<p>Todays Time : <?php echo $todays_time; ?></p>
	<p>This months time : <?php echo $months_time; ?></p>
	<p>Target time : <?php echo $months_target_time; ?></p>
</div>