<?php use Phalcon\Tag as Tag ?>

<div class="sidebar_block well">
	<?php echo Tag::form(array('attendance/savepost')); ?>
		<input type="hidden" name="user_id" value="<?php echo $currentUser->id; ?>">
		<input type="hidden" name="controller" value="<?php echo $this->view->getControllerName(); ?>">
		<input type="hidden" name="action" value="<?php echo $this->view->getActionName() . $extra_params; ?>">

		<?php if (!is_null($attendance)) { ?>
			<input type="hidden" name="attendance_id" value="<?php echo $attendance->id; ?>">
			<button class="btn btn-inverse btn-large sidebar_btn" type="submit">End Time</button>
		<?php } else { ?>
			<button class="btn btn-inverse btn-large sidebar_btn" type="submit">Start Time</button>
			<br /><br />
			<select class="input-block-level" name="task_id">
				<option value="0">No Task</option>

				<?php foreach($tasks_select AS $_task_id => $_task) { ?>
					<option value="<?php echo $_task_id; ?>"><?php echo $_task; ?></option>
				<?php } ?>
			</select>
		<?php } ?>
	</form>

	<p>Todays Time : <?php echo $todays_time; ?></p>
	<p>This months time : <?php echo $months_time; ?></p>
	<p>Target time : <?php echo $months_target_time; ?></p>
</div>