<?php use Phalcon\Tag as Tag ?>

<div class="activity">
	<?php if (count($activities) == 0) { ?>
		<div class="align-center">
			<h5>No activity!</h5>
		</div>
	<?php } else { ?>
		<?php foreach ($activities AS $activity) { ?>
			<a href="<?php echo $this->url->get($activity->getUrl()); ?>" class="activity-preview <?php echo ($activity->read == 0) ? 'new' : ''; ?>">
				<div class="media">
					<img class="media-object pull-left" src="<?php echo $this->url->get('profile/default.jpg'); ?>">

					<abbr class="date pull-right"><?php echo date('D, j M Y H:i:s O', strtotime($activity->created_at)); ?></abbr>

					<div class="media-body">
						<p class="media-heading span6">
							<?php echo $activity->message; ?>
						</p>
					</div>
				</div>
			</a>
		<?php } ?>
	<?php } ?>
</div>
