<?php use Phalcon\Tag as Tag ?>
<div class="navbar-inner">
	<div class="container">
		<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</a>

		<?php if ($currentUser) { ?>
			<a href="<?php echo $this->url->get('dashboard/index'); ?>" class="brand"><?php echo $AppName; ?></a>
		<?php } else if ($controller == 'install') { ?>
			<a href="<?php echo $this->url->get('install/index'); ?>" class="brand"><?php echo $AppName; ?></a>
		<?php } else { ?>
			<a href="<?php echo $this->url->get('user/login'); ?>" class="brand"><?php echo $AppName; ?></a>
		<?php } ?>

		<div class="nav-collapse collapse">
			<?php if ($controller != 'install') { ?>
				<?php if ($currentUser) { ?>
				<ul class="nav pull-left">
					<li <?php echo ($controller == 'dashboard') ? 'class="active"' : ''; ?>>
						<a href="<?php echo $this->url->get('dashboard/index'); ?>">
							<i class="icon-home icon-white"></i>
						</a>
					</li>
					<li class="dropdown <?php echo ($controller == 'project' || $controller == 'task') ? 'active' : ''; ?>">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							Projects
						</a>
						<ul class="dropdown-menu">
							<?php if ($currentUser->isAdmin()) { ?>
								<li>
									<a href="#newProject" data-toggle="modal">
										<i class="icon-plus"></i>
										Add a new project
									</a>
								</li>
								<li class="divider"></li>
							<?php } ?>
							<?php foreach($allProjects AS $project) { ?>
								<li>
									<a href="<?php echo $this->url->get('project/view/' . $project->id); ?>">
										<?php echo $project->name; ?>
									</a>
							<?php } ?>
						</ul>
					</li>
				</ul>
				<?php } ?>

				<ul class="nav pull-right">
					<?php if (!$currentUser) { ?>
						<li class="active">
							<a href="<?php echo $this->url->get('user/login'); ?>">
								Log in
							</a>
						</li>
					<?php } else { ?>
						<li id="header-notification" class="dropdown">
							<?php $this->partial('partials/header_notification'); ?>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<?php echo $currentUser->full_name; ?>
							</a>

							<ul class="dropdown-menu">
								<li>
									<a href="<?php echo $this->url->get('user/logout'); ?>">
										<i class="icon-off"></i>
										Logout
									</a>
								</li>
							</ul>
						</li>
					<?php } ?>
				</ul>
			<?php } ?>
		</div> <!-- .nav-collapse -->
	</div> <!-- .container -->
</div> <!-- .navbar-inner -->
