<?php use Phalcon\Tag as Tag ?>

<form id="timer-form" class="hidden" action="<?php echo $this->url->get('attendance/startstop'); ?>" method="post">
    <input type="hidden" id="timer-form-task-id" value="" name="task_id">
    <input type="hidden" value="<?php echo $controller; ?>" name="controller">
    <input type="hidden" value="<?php echo $action . '/' . $url_params; ?>" name="action">
</form>

<div class="navbar-inner">
    <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>

        <?php if ($currentUser) { ?>
            <a href="<?php echo $this->url->get('dashboard/index'); ?>" class="brand"><?php echo $AppName; ?></a>
        <?php } else if ($controller == 'install') { ?>
            <a href="<?php echo $this->url->get('install/index'); ?>" class="brand"><?php echo $AppName; ?></a>
        <?php } else { ?>
            <a href="<?php echo $this->url->get('user/login'); ?>" class="brand"><?php echo $AppName; ?></a>
        <?php } ?>

        <div class="nav-collapse collapse">
            <?php if ($controller != 'install') { ?>
                <?php if ($currentUser) { ?>
                <ul class="nav pull-left">
                    <li <?php echo ($controller == 'dashboard') ? 'class="active"' : ''; ?>>
                        <a href="<?php echo $this->url->get('dashboard/index'); ?>">
                            <i class="icon-home icon-white"></i>
                        </a>
                    </li>
                    <li class="dropdown <?php echo ($controller == 'project') ? 'active' : ''; ?>">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Projects
                        </a>
                        <ul class="dropdown-menu">
                            <?php if ($currentUser->isAdmin()) { ?>
                                <li>
                                    <a href="#newProject" data-toggle="modal">
                                        <i class="icon-plus"></i>
                                        Add a new project
                                    </a>
                                </li>
                                <li class="divider"></li>
                            <?php } ?>
                            <?php if (count($allProjects) > 0) { ?>
                                <?php foreach($allProjects AS $project) { ?>
                                    <li>
                                        <a href="<?php echo $this->url->get('project/view/' . $project->id); ?>">
                                            <?php echo $project->name; ?>
                                        </a>
                                <?php } ?>
                            <?php } else { ?>
                                <li>
                                    <a href="javascript:void(0)">
                                        No projects for you!
                                    </a>
                                </li>
                            <?php } ?>
                        </ul>
                    </li>
                    <li <?php echo ($controller == 'report') ? 'class="active"' : ''; ?>>
                        <a href="<?php echo $this->url->get('report/attendance'); ?>">
                            Reports
                        </a>
                    </li>
                </ul>
                <?php } ?>

                <ul class="nav pull-right">
                    <?php if (!$currentUser) { ?>
                        <li class="active">
                            <a href="<?php echo $this->url->get('user/login'); ?>">
                                Log in
                            </a>
                        </li>
                    <?php } else { ?>
                        <li id="header-timer" class="dropdown">
                            <a href="#" class="dropdow-toggle" data-toggle="dropdown">
                                <i class="icon-time icon-white"></i>
                            </a>

                            <ul class="dropdown-menu span6">
                                <li>
                                    <div class="align-center">
                                        <h5>
                                            Todays Time :
                                            &nbsp;
                                            <span id="timer-userTodaysTime" class="text-warning">
                                                <?php echo $userTodaysTime; ?>
                                            </span>
                                            <?php if ($currentAttendance) { ?>
                                                &nbsp;&nbsp;|&nbsp;&nbsp;
                                                Current Task Time :
                                                &nbsp;
                                                <span id="timer-currentTaskTime" class="text-warning">
                                                    <?php echo $currentAttendance->getTimeSpent(); ?>
                                                </span>
                                            <?php } ?>
                                        </h5>
                                    </div>
                                </li>
                                <li class="divider"></li>

                                <?php if ($currentAttendance) { ?>
                                    <li>
                                        <a class="timer-task-a" href="#" data-task-id="<?php echo $currentAttendance->task_id; ?>">
                                            <i class="icon-stop"></i>
                                            &nbsp;&nbsp;
                                            <?php if ($currentAttendance->task_id == 0) { ?>
                                                No task
                                            <?php } else { ?>
                                                (<?php echo $currentAttendance->getTask()->getProject()->name; ?>)
                                                &nbsp;
                                                <?php echo $currentAttendance->getTask()->title; ?>
                                            <?php } ?>
                                        </a>
                                    </li>
                                <?php } else { ?>
                                    <li>
                                        <a class="timer-task-a" href="#" data-task-id="0">
                                            <i class="icon-play"></i>
                                            &nbsp;&nbsp;
                                            No Task
                                        </a>
                                    </li>
                                    <?php foreach ($userTasks AS $userTask) { ?>
                                        <li>
                                            <a class="timer-task-a" href="#" data-task-id="<?php echo $userTask->id; ?>">
                                                <i class="icon-play"></i>
                                                &nbsp;&nbsp;
                                                (<?php echo $userTask->getProject()->name; ?>)
                                                &nbsp;
                                                <?php echo $userTask->title; ?>
                                            </a>
                                        </li>
                                    <?php } ?>
                                <?php } ?>
                            </ul>
                        </li>
                        <li id="header-notification" class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <span id="notificationsCount" class="badge badge-important"><?php echo count($notifications); ?></span>
                            </a>

                            <ul class="dropdown-menu">
                                <li>
                                    <?php if (count($notifications) == 0) { ?>
                                        <div id="notificationDropdown" class="activity span6">
                                            <div class="align-center">
                                                <h5>No new notifications!</h5>
                                            </div>
                                        </div>
                                    <?php } else { ?>
                                        <div id="notificationDropdown" class="activity span6">
                                            <?php foreach ($notifications AS $notification) { ?>
                                                <a href="<?php echo $this->url->get($notification->getUrl()); ?>" class="activity-preview new">
                                                    <div class="media">
                                                        <img class="media-object pull-left" src="<?php echo $this->url->get('profile/default.jpg'); ?>">

                                                        <abbr class="date pull-right"><?php echo date('D, j M Y H:i:s O', strtotime($notification->created_at)); ?></abbr>

                                                        <div class="media-body">
                                                            <p class="media-heading span4">
                                                                <?php echo $notification->message; ?>
                                                            </p>
                                                        </div>
                                                    </div>
                                                </a>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>
                                </li>
                            </ul>
                        </li>
                        <li class="dropdown <?php echo ($controller == 'user' || $controller == 'admin') ? 'active' : ''; ?>">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <?php echo $currentUser->full_name; ?>
                            </a>

                            <ul class="dropdown-menu">
                                <li>
                                    <a href="<?php echo $this->url->get('user/account'); ?>">
                                        <i class="icon-user"></i>
                                        &nbsp;&nbsp;
                                        My Account
                                    </a>
                                </li>
                                <?php if ($currentUser->isAdmin()) { ?>
                                    <li>
                                        <a href="<?php echo $this->url->get('admin/index'); ?>">
                                            <i class="icon-cogs"></i>
                                            &nbsp;&nbsp;
                                            Admin
                                        </a>
                                    </li>
                                <?php } ?>
                                <li class="divider"></li>
                                <li>
                                    <a href="<?php echo $this->url->get('user/logout'); ?>">
                                        <i class="icon-off"></i>
                                        &nbsp;&nbsp;
                                        Logout
                                    </a>
                                </li>
                            </ul>
                        </li>
                    <?php } ?>
                </ul>
            <?php } ?>
        </div> <!-- .nav-collapse -->
    </div> <!-- .container -->
</div> <!-- .navbar-inner -->
