<?php use Phalcon\Tag as Tag ?>

<div id="newTask" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3>Add a new task</h3>
	</div>

	<?php echo Tag::form(array('project/newtask/' . $currentProject->id, 'class' => 'form-horizontal')); ?>
		<div class="modal-body">
			<div class="control-group">
				<label class="control-label" for="newTaskTitle">Task title</label>
				<div class="controls">
					<input type="text" class="input-block-level" placeholder="Task title" name="title" id="newTaskTitle">
					<input type="hidden" value="<?php echo $controller; ?>" name="controller">
						<input type="hidden" value="<?php echo $action . '/' . $url_params; ?>" name="action">
				</div>
			</div>
		</div>

		<div class="modal-footer">
			<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
			<button class="btn btn-primary">Create Task</button>
		</div>
	</form>
</div>
