<?php use Phalcon\Tag as Tag ?>

<?php if (($controller == 'user' && $action == 'login') || $controller == 'install') { ?>
    <br>
    <br>
    <br>
    <br>
    <br>
<?php } else if ($controller == 'dashboard' || $controller == 'user') { ?>
    <ul>
        <li>
            <div class="span2 knob">
                <h4>Open Tasks</h4>
                <div id="taskPercent" class="chart" data-percent="<?php echo $taskPercent; ?>">
                    <span id="openTasksCount"><?php echo $openTasksCount; ?></span>
                    /
                    <span id="allTasksCount"><?php echo $allTasksCount; ?></span>
                </div>
            </div>
        </li>
        <li>
            <div class="span2 knob">
                <h4>Productivity</h4>
                    <div id="userTodaysProductivity" class="chart" data-percent="<?php echo $userTodaysProductivity; ?>">
                        <span id="userTodaysProductivityText"><?php echo $userTodaysProductivity; ?></span>%
                    </div>
            </div>
        </li>
        <li>
            <div class="span2 knob">
                <h4>Todays Time</h4>
                <div id="userTodaysTimePercent" class="chart" data-percent="<?php echo $userTodaysTimePercent; ?>">
                    <span id="userTodaysTime"><?php echo $userTodaysTime; ?></span>
                </div>
            </div>
        </li>
        <li>
            <div class="span2 knob">
                <h4>Month's Time</h4>
                <div id="userMonthsTimePercent" class="chart" data-percent="<?php echo $userMonthsTimePercent; ?>">
                    <span id="userMonthsTime"><?php echo $userMonthsTime; ?></span>
                </div>
            </div>
        </li>
    </ul>
<?php } else if ($controller == 'project') { ?>
    <ul>
        <li>
            <a href="<?php echo $this->url->get('project/view/' . $currentProject->id); ?>" <?php echo ($action == 'view') ? 'class="active"' : ''; ?>>
                <i class="icon-tasks icon-4x"></i>
                <br>
                Tasks
            </a>
        </li>
        <li>
            <a href="<?php echo $this->url->get('project/notes/' . $currentProject->id); ?>" <?php echo ($action == 'notes') ? 'class="active"' : ''; ?>>
                <i class="icon-file icon-4x"></i>
                <br>
                Notes
            </a>
        </li>
        <li>
            <a href="<?php echo $this->url->get('project/files/' . $currentProject->id); ?>" <?php echo ($action == 'files') ? 'class="active"' : ''; ?>>
                <i class="icon-cloud icon-4x"></i>
                <br>
                Files
            </a>
        </li>
        <?php if ($currentUser->isAdmin()) { ?>
        <li>
            <a href="<?php echo $this->url->get('project/manage/' . $currentProject->id); ?>" <?php echo ($action == 'manage') ? 'class="active"' : ''; ?>>
                <i class="icon-cogs icon-4x"></i>
                <br>
                Manage
            </a>
        </li>
        <?php } ?>
    </ul>
<?php } else if ($controller == 'admin') { ?>
    <ul>
        <li>
            <a href="<?php echo $this->url->get('admin/index'); ?>" <?php echo ($action == 'index') ? 'class="active"' : ''; ?>>
                <i class="icon-cogs icon-4x"></i>
                <br>
                Manage
            </a>
        </li>
        <li>
            <a href="<?php echo $this->url->get('admin/users'); ?>" <?php echo ($action == 'users') ? 'class="active"' : ''; ?>>
                <i class="icon-group icon-4x"></i>
                <br>
                Users
            </a>
        </li>
        <li>
            <a href="<?php echo $this->url->get('admin/leaves'); ?>" <?php echo ($action == 'leaves') ? 'class="active"' : ''; ?>>
                <i class="icon-calendar icon-4x"></i>
                <br>
                Leaves
            </a>
        </li>
    </ul>
<?php } ?>
