<?php use Phalcon\Tag as Tag ?>

<div class="row">
	<div class="span9">
		<?php $this->partial("partials/projectTop") ?>

		<div class="content_block well">
			<h4>Files</h4>

			<?php echo Tag::form(array('files/post/' . $project->id . '/', 'id' => 'fileupload', 'class' => 'form-horizontal', 'enctype' => 'multipart/form-data')); ?>
		        <div class="row fileupload-buttonbar">
		            <div class="span7">
		                <!-- The fileinput-button span is used to style the file input field as button -->
		                <span class="btn btn-success fileinput-button">
		                    <i class="icon-plus icon-white"></i>
		                    <span>Add files...</span>
		                    <input type="file" name="files[]" multiple>
		                </span>
		                <button type="submit" class="btn btn-primary start">
		                    <i class="icon-upload icon-white"></i>
		                    <span>Start upload</span>
		                </button>
		            </div>
		        </div>

		        <br>

		        <!-- The table listing the files available for upload/download -->
		        <table role="presentation" class="table fileUploads"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody></table>
		    </form>

		    <!-- modal-gallery is the modal dialog used for the image gallery -->
			<div id="modal-gallery" class="modal modal-gallery hide fade" data-filter=":odd" tabindex="-1">
			    <div class="modal-header">
			        <a class="close" data-dismiss="modal">&times;</a>
			        <h3 class="modal-title"></h3>
			    </div>
			    <div class="modal-body"><div class="modal-image"></div></div>
			    <div class="modal-footer">
			        <a class="btn modal-download" target="_blank">
			            <i class="icon-download"></i>
			            <span>Download</span>
			        </a>
			        <a class="btn btn-success modal-play modal-slideshow" data-slideshow="5000">
			            <i class="icon-play icon-white"></i>
			            <span>Slideshow</span>
			        </a>
			        <a class="btn btn-info modal-prev">
			            <i class="icon-arrow-left icon-white"></i>
			            <span>Previous</span>
			        </a>
			        <a class="btn btn-primary modal-next">
			            <span>Next</span>
			            <i class="icon-arrow-right icon-white"></i>
			        </a>
			    </div>
			</div>

			<!-- The template to display files available for upload -->
			<script id="template-upload" type="text/x-tmpl">
			{% for (var i=0, file; file=o.files[i]; i++) { %}
			    <tr class="template-upload fade fileUpload">
					<td class="preview">
						<span class="fade"></span>
					</td>

					<td class="content">
						<p>
							{%=file.name%}
						</p>

						<p>
							{%=o.formatFileSize(file.size)%}
						</p>

						{% if (!file.error) { %}
							<div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="bar" style="width:0%;"></div></div>

							<p>
								<span class="start">
									<button class="btn btn-primary">
				                    	<i class="icon-upload icon-white"></i>
				                    	<span>Start</span>
				                	</button>
			                	</span>&nbsp;&nbsp;
						{% } else { %}
							<p>
						{% } %}

							<span class="cancel">
								<button class="btn btn-warning">
					                <i class="icon-ban-circle icon-white"></i>
					                <span>Cancel</span>
					            </button>
					        </span>
				        </p>
					</td>
				</tr>
			{% } %}
			</script>
			<!-- The template to display files available for download -->
			<script id="template-download" type="text/x-tmpl">
			{% for (var i=0, file; file=o.files[i]; i++) { %}
				{% if (!file.error) { %}
					<tr class="template-download fade fileUpload">
						<td class="preview">
							{% if (file.thumbnail_url) { %}
								<a href="{%=file.url%}" title="{%=file.name%}" data-gallery="gallery" download="{%=file.name%}">
									<img src="{%=file.thumbnail_url%}" width="128" alt="{%=file.name%}">
								</a>
							{% } else { %}
								<div class="{%=file.type%}"></div>
							{% } %}
						</td>
						<td class="content">
							<p>
								<a href="{%=file.url%}" title="{%=file.name%}" data-gallery="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
							</p>
							<p>
								{%=o.formatFileSize(file.size)%}
							</p>
							<p>
								Uploaded by {%=file.uploaded_by%} at {%=file.uploaded_at%}
							</p>

							{% if (file.delete_url) { %}
								<p>
									<span class="delete">
										<button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
							                <i class="icon-trash icon-white"></i>
							                <span>Delete</span>
							            </button>
						            </span>
						        </p>
							{% } %}
						</td>
					</tr>
				{% } %}
			{% } %}
			</script>
		</div>
	</div>

	<div class="span3">
		<?php $this->partial("partials/attendance") ?>

		<?php $this->partial("partials/projectUsers") ?>
	</div>

	<script type="text/javascript">
		$('#fileupload').fileupload({
   			prependFiles : true,
   			previewMaxWidth: 128
	    });

	    $.ajax({
            url: '<?php echo $this->url->get('files/get/' . $project->id . '/'); ?>',
            dataType: 'json',
            context: $('#fileupload')[0]
        }).done(function (result) {
            $(this).fileupload('option', 'done')
                .call(this, null, {result: result});
        });
	</script>
</div>
