<?php use Phalcon\Tag as Tag ?>

<div class="row">
	<div class="span9">
		<?php if (count($allProjects) > 0) { ?>
			<?php $_i = 0; ?>

			<?php foreach($allProjects AS $project) { ?>
				<?php if ($_i % 3 == 0) { ?>
					<div class="row">
				<?php } ?>

				<div class="span3 projectCard">
					<div class="well well-small content_block">
						<a href="<?php echo $this->url->get('project/view/' . $project->id . '/'); ?>">
							<h4><?php echo $project->name; ?></h4>

							<div class="description">
								<?php echo Markdown($project->description); ?>
							</div>

							<p class="muted summary">
								<?php
									$_usersToolTipHtml = '';

									foreach($project->getDevelopers() AS $_devloper) {
										$_usersToolTipHtml .= '<p>' . $_devloper->full_name . '</p>';
									}

									$_tasksToolTipHtml = '';

									$_openTasks = $project->getOpenTasks(5);

									if (count($_openTasks) > 0) {
										foreach($_openTasks AS $_task) {
											$_tasksToolTipHtml .= '<p>' . $_task->title . '</p>';
										}
									}
								?>
								<span rel="tooltip" data-placement="right" data-html="true" data-original-title="<?php echo $_usersToolTipHtml; ?>"><?php echo count($project->getDevelopers()); ?> users</span>,&nbsp;
								<span rel="tooltip" data-placement="right" data-html="true" data-original-title="<?php echo $_tasksToolTipHtml; ?>"><?php echo count($project->getOpenTasks()); ?> open tasks</span>
							</p>
						</a>
					</div>
				</div>

				<?php if (($_i + 1) % 3 == 0 || ($_i + 1) == count($allProjects)) { ?>
					</div>
				<?php } ?>

				<?php $_i++; ?>
			<?php } ?>
		<?php } else { ?>
			<div class="content_block well well-large">
				<p>You are not into any project.</p>
			</div>
		<?php } ?>
	</div>

	<div class="span3">
		<?php $this->partial("partials/attendance") ?>

		<?php if($canCreateProject) { ?>
			<a href="#newProject" role="button" class="btn btn-primary btn-large input-block-level" data-toggle="modal">Add a new project</a>

			<div id="newProject" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
					<h3>Add a new project</h3>
				</div>

				<?php echo Tag::form(array('project/createpost', 'class' => 'form-horizontal')); ?>
					<div class="modal-body">
						<div class="control-group">
							<label class="control-label" for="newProjectName">Name</label>
							<div class="controls">
								<input type="text" class="input-block-level" placeholder="Project Name" name="name" id="newProjectName">
							</div>
						</div>

						<div class="control-group">
							<label class="control-label" for="newProjectDescription">Description</label>
							<div class="controls">
								<textarea rows="6" class="input-block-level" name="description" placeholder="Project Description" id="newProjectDescription"></textarea>
							</div>
						</div>

						<input type="hidden" value="project" name="controller">
						<input type="hidden" value="index" name="action">
					</div>

					<div class="modal-footer">
						<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
						<button class="btn btn-primary">Save changes</button>
					</div>
				</form>
			</div>
		<?php } ?>
	</div>
</div>
