<?php use Phalcon\Tag as Tag ?>


<div class="span12 header">
	<a href="#" class="btn pull-right">
		<i class="icon-plus"></i>
		New Task
	</a>
	<h4>Tasks</h4>
</div>

<?php if (!$currentTask) { ?>
<div class="span12 align-center">
	<h5>No tasks for this Project! Why not add some?</h5>
</div>
<?php } else { ?>
<div class="span4">
	<div class="message-sidebar">
		<?php foreach($allProjectTasks AS $projectTask) { ?>
			<a href="<?php echo $this->url->get('project/view/' . $currentProject->id . '/' . $projectTask->id); ?>" class="message-preview <?php echo ($projectTask->status == 0) ? 'new' : ''; ?> <?php echo ($projectTask->id == $currentTask->id) ? 'active' : ''; ?>">
				<abbr class="date pull-right"><?php echo date('D, j M Y H:i:s O', strtotime($projectTask->created_at)); ?></abbr>
				<h5>
					<?php echo $projectTask->getUser()->full_name; ?>
					&nbsp;&nbsp;&nbsp;
					<span>
						<i class="icon-comments"></i>
						<?php echo count($projectTask->getComment()); ?>
					</span>
				</h5>
				<h6><?php echo $projectTask->title; ?></h6>
				<?php if ($projectTask->status == 0 && $projectTask->hours > 0) { ?>
					<div class="progress">
						<div style="width: <?php echo $projectTask->getTimePercent(); ?>%;" class="bar bar-success"></div>
					</div>
				<?php } ?>
			</a>
		<?php } ?>
	</div>
</div>

<div class="span8">
	<div class="messages">
		<span class="pull-right">
			&nbsp;
			<span>
				Spent : <a href="#" id="task_hours_spent" class="editable editable-click"><?php echo $currentTask->getTotalTimeSpent(); ?></a>
			</span>
			&nbsp;
			<span>
				Status : <a href="#" id="task_status" data-name="status" data-type="select" data-pk="<?php echo $currentTask->id; ?>" data-url="<?php echo $this->url->get('task/updateajax'); ?>" data-value="<?php echo $currentTask->status; ?>" data-source="[{value: 0, text: 'Open'}, {value: 1, text: 'Closed'}]" data-placement="left" data-original-title="Status" class="editable editable-click"><?php echo ($currentTask->status == 0) ? 'Open' : 'Closed'; ?></a>
			</span>
		</span>
		<h4 class="header">
			<a href="#" id="task_title" data-name="title" data-type="text" data-pk="<?php echo $currentTask->id; ?>" data-url="<?php echo $this->url->get('task/updateajax'); ?>" data-original-title="Enter Task Title" class="editable editable-click"><?php echo $currentTask->title; ?></a>
		</h4>
		<p class="header_bottom">
			<span>
				Job ID : <a href="#" id="task_job_id" data-name="job_id" data-type="text" data-pk="<?php echo $currentTask->id; ?>" data-url="<?php echo $this->url->get('task/updateajax'); ?>" data-original-title="Enter Job ID" class="editable editable-click"><?php echo $currentTask->job_id; ?></a>
			</span>
			&nbsp;
			<span>
				Assigned to : <a href="#" id="task_assigned_to" data-name="assigned_to" data-type="select" data-pk="<?php echo $currentTask->id; ?>" data-url="<?php echo $this->url->get('task/updateajax'); ?>" data-value="<?php echo $currentTask->assigned_to; ?>" data-source="<?php echo $this->url->get('project/getusersajax/' . $currentProject->id ); ?>" data-original-title="Assigned To" class="editable editable-click"><?php echo $currentTask->getUser()->full_name; ?></a>
			</span>
			&nbsp;
			<span>
				Hours : <a href="#" id="task_hours" data-name="hours" data-type="number" data-pk="<?php echo $currentTask->id; ?>" data-url="<?php echo $this->url->get('task/updateajax'); ?>" data-original-title="Hours" class="editable editable-click"><?php echo $currentTask->getHours(); ?></a>
			</span>

			<a href="#task_people" class="pull-right">
				<i class="icon-group"></i>
				People
			</a>
		</p>

		<?php foreach ($currentTask->getComments() AS $comment) { ?>
			<div class="message" id="comment-<?php echo $comment->id; ?>">
				<img src="<?php echo $this->url->get('profile/default.jpg'); ?>" class="img-rounded pull-left">

				<div class="message-body">
					<abbr class="date pull-right"><?php echo date('D, j M Y H:i:s O', strtotime($comment->created_at)); ?></abbr>
					<h5><?php echo $comment->getUser()->full_name; ?></h5>

					<?php echo $comment->comment; ?>
				</div>
			</div>
		<?php } ?>

		<div class="message">
			<img src="<?php echo $this->url->get('profile/default.jpg'); ?>" class="img-rounded pull-left">
			<div class="message-body">
				<h5>Post a Comment</h5>
				<textarea id="comment-textarea" class="input-block-level" rows="6"></textarea>

				<p>
					<a href="#" class="btn">Post Comment</a>
				</p>
			</div>
		</div>

	</div>
</div>
<?php } ?>
