<?php use Phalcon\Tag as Tag ?>

<div class="span8">
    <h4 class="header">Attendance Report</h4>

    <table id="attendance_report_table" class="table table-bordered table-hover align-center">
        <thead>
            <tr>
                <th>Date</th>
                <th>Day</th>
                <th>Target Time</th>
                <th>Time Logged</th>
                <th>Productivity</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($records['items'] AS $row) { ?>
                <?php
                    $_tr_class = '';

                    if ($row['Weekoffs']) {
                        $_tr_class = 'warning';
                    }
                    else if ($row['Holiday']) {
                        $_tr_class = 'info';
                    }
                    else if ($row['Leaves']) {
                        $_tr_class = 'success';
                    }
                ?>
                <tr class="<?php echo $_tr_class; ?>">
                    <td><?php echo $row['Date']; ?></td>
                    <td><?php echo $row['Day']; ?></td>
                    <td><?php echo $row['TargetTime']; ?></td>
                    <td><?php echo $row['LoggedTime']; ?></td>
                    <td><?php echo $row['Productivity']; ?></td>
                </tr>
            <?php } ?>
        </tbody>
        <tfoot>
            <tr>
                <td>Total</td>
                <td>&nbsp;</td>
                <td><?php echo $records['MonthsTargetTime']; ?></td>
                <td><?php echo $records['MonthsTime']; ?></td>
                <td><?php echo $records['MonthsProductivity']; ?></td>
            </tr>
        </tfoot>
    </table>
</div>

<div class="span4">
    <h4 class="header">Filter By</h4>

    <form action="<?php echo $this->url->get('report/attendance'); ?>" method="post">
        <p>
            <label for="attendanceMonth">Month</label>
            <select id="attendanceMonth" name="month">
                <option value="01" <?php echo ($attendanceMonth == "01") ? 'selected="selected"' : ''; ?>>January</option>
                <option value="02" <?php echo ($attendanceMonth == "02") ? 'selected="selected"' : ''; ?>>February</option>
                <option value="03" <?php echo ($attendanceMonth == "03") ? 'selected="selected"' : ''; ?>>March</option>
                <option value="04" <?php echo ($attendanceMonth == "04") ? 'selected="selected"' : ''; ?>>April</option>
                <option value="05" <?php echo ($attendanceMonth == "05") ? 'selected="selected"' : ''; ?>>May</option>
                <option value="06" <?php echo ($attendanceMonth == "06") ? 'selected="selected"' : ''; ?>>June</option>
                <option value="07" <?php echo ($attendanceMonth == "07") ? 'selected="selected"' : ''; ?>>July</option>
                <option value="08" <?php echo ($attendanceMonth == "08") ? 'selected="selected"' : ''; ?>>August</option>
                <option value="09" <?php echo ($attendanceMonth == "09") ? 'selected="selected"' : ''; ?>>September</option>
                <option value="10" <?php echo ($attendanceMonth == "10") ? 'selected="selected"' : ''; ?>>October</option>
                <option value="11" <?php echo ($attendanceMonth == "11") ? 'selected="selected"' : ''; ?>>November</option>
                <option value="12" <?php echo ($attendanceMonth == "12") ? 'selected="selected"' : ''; ?>>December</option>
            </select>
        </p>

        <p>
            <label for="attendanceYear">Year</label>
            <select id="attendanceYear" name="year">
                <option value="2012" <?php echo ($attendanceYear == "2012") ? 'selected="selected"' : ''; ?>>2012</option>
                <option value="2013" <?php echo ($attendanceYear == "2013") ? 'selected="selected"' : ''; ?>>2013</option>
                <option value="2014" <?php echo ($attendanceYear == "2014") ? 'selected="selected"' : ''; ?>>2014</option>
                <option value="2015" <?php echo ($attendanceYear == "2015") ? 'selected="selected"' : ''; ?>>2015</option>
                <option value="2016" <?php echo ($attendanceYear == "2016") ? 'selected="selected"' : ''; ?>>2016</option>
            </select>
        </p>

        <?php if ($currentUser->isAdmin()) { ?>
            <p>
                <label for="attendanceUser">User</label>
                <select id="attendanceUser" name="user_id">
                    <?php foreach ($allUsers AS $_user) { ?>
                        <option value="<?php echo $_user->id; ?>" <?php echo ($_user->id == $attendanceUserId) ? 'selected="selected"' : ''; ?>>
                            <?php echo $_user->full_name; ?>
                        </option>
                    <?php } ?>
                </select>
            </p>
        <?php } ?>

        <p>
            <button type="submit" class="btn">Generate</button>
        </p>
    </form>
</div>
