<?php use Phalcon\Tag as Tag ?>

<input type="hidden" id="reportSummaryUserId" value="<?php echo $reportSummaryUserId; ?>">
<input type="hidden" id="reportSummaryStartDate" value="<?php echo $reportSummaryStartDate; ?>">
<input type="hidden" id="reportSummaryPrevAjaxUrl" value="<?php echo $this->url->get('report/getajaxreportprev'); ?>">
<input type="hidden" id="reportSummaryNextAjaxUrl" value="<?php echo $this->url->get('report/getajaxreportnext'); ?>">

<?php if ($currentUser->isAdmin()) { ?>
    <div class="span3">
        <ul class="nav nav-tabs nav-stacked">
            <?php foreach ($allUsers AS $user) { ?>
                <li class="<?php echo ($user->id == $reportSummaryUserId) ? 'active' : ''; ?>">
                    <a href="<?php echo $this->url->get('report/index/' . $user->id); ?>" class="a-show-loader"><?php echo $user->full_name; ?></a>
                </li>
            <?php } ?>
        </ul>
    </div>
<?php } ?>

<div class="<?php echo ($currentUser->isAdmin()) ? 'span9' : 'span12'; ?>">
    <?php if ($currentUser->id == $reportSummaryUser->id) { ?>
        <h4 class="header">Your Summary</h4>
        <?php $_fullName = 'You'; ?>
        <?php $_has = 'have'; ?>
    <?php } else { ?>
        <h4 class="header">Summary for <?php echo $reportSummaryUser->full_name; ?></h4>
        <?php $_fullName = $reportSummaryUser->full_name; ?>
        <?php $_has = 'has'; ?>
    <?php } ?>

    <?php if (is_null($attendanceStat)) { ?>
        <p>No data present to display!</p>
    <?php } else { ?>
        <p>
            <?php echo $_fullName; ?> usually comes to office at <?php echo $attendanceStat['avgStartTime']; ?> and leaves at <?php echo $attendanceStat['avgEndTime']; ?>.
        </p>
        <p>
            <?php echo $_fullName; ?> usually works for <?php echo $attendanceStat['avgLoggedHours']; ?> hours out of <?php echo $attendanceStat['avgTotalHours']; ?> hours present in office, with an average productivity of <?php echo $attendanceStat['avgProductivity']; ?>.
        </p>
        <p>
            <?php echo $_fullName; ?> usually works on <?php echo $attendanceStat['avgNoRealTasksWorked']; ?> billable tasks per day with an average of <?php echo $attendanceStat['avgTimeOnRealTasks']; ?> hours for them.
        </p>
        <p>
            <?php echo $_fullName; ?> <?php echo $_has; ?> worked <?php echo $attendanceStat['daysWorked']; ?> out of <?php echo $attendanceStat['workingDays']; ?> days, (<?php echo $attendanceStat['leavesApproved']; ?> approved leaves, <?php echo $attendanceStat['unscheduledLeaves']; ?> unscheduled leaves).
        </p>
    <?php } ?>

    <br>
    <br>

    <span class="pull-right">
        <button id="reportSummaryChartsPrev" class="btn btn-small">Prev</button>
        &nbsp;
        <button id="reportSummaryChartsNext" class="btn btn-small">Next</button>
    </span>
    <div id="reportSummaryCharts">
        <h4 class="header">
            Charts (Between <span id="reportSummaryBetween"><?php echo $reportSummaryStartDate; ?> to <?php echo $reportSummaryEndDate; ?></span>)
        </h4>
        <div id="reportSummaryChartsLoading">
            <h4>
                <i class="icon-spinner icon-spin icon-4x"></i>
            </h4>
        </div>

        <div id="reportSummaryChartsContent">
            <?php $this->partial('report/report_summary_charts'); ?>
        </div>
    </div>
</div>