<?php use Phalcon\Tag as Tag ?>

<div class="row">
	<div class="span9">
		<div class="content_block well">
			<?php echo Tag::form(array('report/index', 'class' => 'form-inline')); ?>
				<input type="text" class="input-small jdpicker clickToClose" placeholder="From" name="from" value="<?php echo $post_from; ?>">
				&nbsp;&nbsp;&nbsp;
				<input type="text" class="input-small jdpicker clickToClose" placeholder="To" name="to" value="<?php echo $post_to; ?>">
				&nbsp;&nbsp;&nbsp;

				<?php if (!is_null($allUsers)) { ?>
					<select name="user_id">
						<?php foreach($allUsers AS $_user) { ?>
							<option value="<?php echo $_user->id; ?>" <?php echo ($post_user_id == $_user->id) ? 'selected="selected"' : ''; ?>><?php echo $_user->full_name; ?></option>
						<?php } ?>
					</select>
					&nbsp;&nbsp;&nbsp;
				<?php } ?>
				<button type="submit" class="btn">Generate report</button>
			</form>
			<table class="table table-bordered table-striped">
				<thead>
					<tr>
						<th>Date</th>
						<th>Task</th>
						<th>Time Spent</th>
					</tr>
				</thead>
				<tbody>
					<?php if (is_null($reports) || count($reports) == 0) { ?>
						<tr>
							<td colspan="3" class="a-center">
								No reports!
							</td>
						</tr>
					<?php } else { ?>
						<?php foreach($reports AS $row) { ?>
							<tr>
								<td><?php echo $row['date']; ?></td>
								<td><?php echo $row['task_title']; ?></td>
								<td><?php echo $row['time_spent']; ?></td>
							</tr>
						<?php } ?>
					<?php } ?>
				</tbody>
			</table>
		</div>
	</div>

	<div class="span3">
		<?php $this->partial("partials/attendance") ?>
	</div>
</div>