<?php use Phalcon\Tag as Tag ?>

<div class="span9">
    <h4 class="header">Work Report</h4>

    <table id="work_report_table" class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Date</th>

                <?php if ($currentUser->isAdmin()) { ?>
                    <th>User</th>
                <?php } ?>

                <th>Job ID</th>
                <th>Project</th>
                <th>Task</th>
                <th>Time Spent</th>
            </tr>
        </thead>
        <tbody>
            <?php if (count($records) > 0) { ?>
                <?php foreach ($records AS $row) { ?>
                    <tr>
                        <td><?php echo $row['Date']; ?></td>

                        <?php if ($currentUser->isAdmin()) { ?>
                            <td><?php echo $row['User']; ?></td>
                        <?php } ?>

                        <td><?php echo $row['JobId']; ?></td>
                        <td><?php echo $row['Project']; ?></td>
                        <td><?php echo $row['Task']; ?></td>
                        <td><?php echo $row['TimeSpent']; ?></td>
                    </tr>
                <?php } ?>
            <?php } else { ?>
                <?php if ($currentUser->isAdmin()) { ?>
                    <tr>
                        <td colspan="6" class="a-center">
                            No reports!
                        </td>
                    </tr>
                <?php } else { ?>
                    <tr>
                        <td colspan="5" class="a-center">
                            No reports!
                        </td>
                    </tr>
                <?php } ?>
            <?php } ?>
        </tbody>
    </table>
</div>

<div class="span3">
    <h4 class="header">Filter By</h4>

    <form action="<?php echo $this->url->get('report/workreport'); ?>" method="post">
        <p>
            <label for="workreportFrom">From</label>
            <input type="text" name="workreportFrom" value="<?php echo $workreportStartDate; ?>" data-date-format="yyyy-mm-dd" id="workreportFrom" class="datepicker" readonly>
        </p>

        <p>
            <label for="workreportTo">To</label>
            <input type="text" name="workreportTo" value="<?php echo $workreportEndDate; ?>" data-date-format="yyyy-mm-dd" id="workreportTo" class="datepicker" readonly>
        </p>

        <?php if ($currentUser->isAdmin()) { ?>
            <p>
                <label for="workreportUser">User</label>
                <select id="workreportUser" name="user_id">
                    <option value="0" <?php echo ($workreportUserId == 0) ? 'selected="selected"' : ''; ?>>
                        All Users
                    </option>

                    <?php foreach ($allUsers AS $_user) { ?>
                        <option value="<?php echo $_user->id; ?>" <?php echo ($_user->id == $workreportUserId) ? 'selected="selected"' : ''; ?>>
                            <?php echo $_user->full_name; ?>
                        </option>
                    <?php } ?>
                </select>
            </p>
        <?php } ?>

        <p>
            <button type="submit" class="btn a-show-loader">Generate</button>
        </p>
    </form>
</div>
