<?php use Phalcon\Tag as Tag ?>

<div class="row">
	<div class="span9">
		<div class="content_block well">
			<?php echo Tag::form(array('attendance/index', 'class' => 'form-inline')); ?>
				<select name="month" class="input-small">
					<option value="01" <?php echo ($post_month == "01") ? 'selected="selected"' : ''; ?>>January</option>
					<option value="02" <?php echo ($post_month == "02") ? 'selected="selected"' : ''; ?>>February</option>
					<option value="03" <?php echo ($post_month == "03") ? 'selected="selected"' : ''; ?>>March</option>
					<option value="04" <?php echo ($post_month == "04") ? 'selected="selected"' : ''; ?>>April</option>
					<option value="05" <?php echo ($post_month == "05") ? 'selected="selected"' : ''; ?>>May</option>
					<option value="06" <?php echo ($post_month == "06") ? 'selected="selected"' : ''; ?>>June</option>
					<option value="07" <?php echo ($post_month == "07") ? 'selected="selected"' : ''; ?>>July</option>
					<option value="08" <?php echo ($post_month == "08") ? 'selected="selected"' : ''; ?>>August</option>
					<option value="09" <?php echo ($post_month == "09") ? 'selected="selected"' : ''; ?>>September</option>
					<option value="10" <?php echo ($post_month == "10") ? 'selected="selected"' : ''; ?>>October</option>
					<option value="11" <?php echo ($post_month == "11") ? 'selected="selected"' : ''; ?>>November</option>
					<option value="12" <?php echo ($post_month == "12") ? 'selected="selected"' : ''; ?>>December</option>
				</select>
				&nbsp;&nbsp;&nbsp;

				<select name="year" class="input-small">
					<option value="2012" <?php echo ($post_year == "2012") ? 'selected="selected"' : ''; ?>>2012</option>
					<option value="2013" <?php echo ($post_year == "2013") ? 'selected="selected"' : ''; ?>>2013</option>
					<option value="2014" <?php echo ($post_year == "2014") ? 'selected="selected"' : ''; ?>>2014</option>
					<option value="2015" <?php echo ($post_year == "2015") ? 'selected="selected"' : ''; ?>>2015</option>
					<option value="2016" <?php echo ($post_year == "2016") ? 'selected="selected"' : ''; ?>>2016</option>
				</select>
				&nbsp;&nbsp;&nbsp;

				<?php if (!is_null($allUsers)) { ?>
					<select name="user_id">
						<?php foreach($allUsers AS $_user) { ?>
							<option value="<?php echo $_user->id; ?>" <?php echo ($post_user_id == $_user->id) ? 'selected="selected"' : ''; ?>><?php echo $_user->full_name; ?></option>
						<?php } ?>
					</select>
					&nbsp;&nbsp;&nbsp;
				<?php } ?>
				<button type="submit" class="btn">Generate report</button>
			</form>

			<table class="table table-bordered">
				<thead>
					<tr>
						<th>Date</th>
						<th>Day</th>
						<th>Target Time</th>
						<th>Time logged</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach($records AS $row) { ?>
						<?php
							$_tr_class = '';

							if ($row['logged_time'] == '00:00:00') {
								$_tr_class = 'not_logged';
							}

							if ($row['holiday'] == true) {
								$_tr_class = 'holiday';
							}

							if (in_array($row['day'], array('Sunday', 'Saturday'))) {
								$_tr_class = 'weekend';
							}
						?>
						<tr class="<?php echo $_tr_class; ?>">
							<td><?php echo $row['date']; ?></td>
							<td><?php echo $row['day']; ?></td>
							<td><?php echo $row['target_time']; ?></td>
							<td><?php echo $row['logged_time']; ?></td>
						</tr>
					<?php } ?>
				</tbody>
				<tfoot>
					<tr>
						<td>Total</td>
						<td>&nbsp;</td>
						<td><?php echo $report_months_target_time; ?></td>
						<td><?php echo $report_months_total_time; ?></td>
					</tr>
				</tfoot>
			</table>
		</div>
	</div>

	<div class="span3">
		<?php $this->partial("partials/attendance") ?>
	</div>
</div>
