<?php use Phalcon\Tag as Tag ?>

<div class="span4">
    <?php $this->partial('partials/user_sidenav'); ?>
</div>

<div class="span8">
    <h4 class="header">Manage your account</h4>

    <form action="<?php echo $this->url->get('user/save'); ?>" class="form-horizontal" method="post" enctype="multipart/form-data">
        <div class="control-group">
            <label class="control-label" for="userAccountProfilePic">Profile Picture</label>
            <div class="controls">
                <img src="<?php echo $this->url->get('profile/' . $currentUser->getProfilePicture()); ?>" class="img-rounded pull-left">
                &nbsp;&nbsp;
                <input type="file" name="profile_pic" id="userAccountProfilePic">
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="userAccountFullName">Full Name</label>
            <div class="controls">
                <input type="text" name="full_name" id="userAccountFullName" value="<?php echo $currentUser->full_name; ?>" required="required">
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="userAccountEmail">Email</label>
            <div class="controls">
                <input type="email" name="email" id="userAccountEmail" value="<?php echo $currentUser->email; ?>" autocomplete="off" required="required">
            </div>
        </div>

        <input type="hidden" name="controller" value="<?php echo $controller; ?>">
        <input type="hidden" name="action" value="<?php echo $action . '/' . $url_params; ?>">

        <div class="control-group">
            <div class="controls">
                <button type="submit" class="btn">Save</button>
            </div>
        </div>
    </form>

    <h4 class="header">Change Password</h4>

    <form action="<?php echo $this->url->get('user/changepassword'); ?>" class="form-horizontal" method="post">
        <div class="control-group">
            <label class="control-label" for="userAccountOldPassword">Old Password</label>
            <div class="controls">
                <input type="password" name="old_password" id="userAccountOldPassword" autocomplete="off" required="required">
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="userAccountNewPassword1">New Password</label>
            <div class="controls">
                <input type="password" name="new_password1" id="userAccountNewPassword1" autocomplete="off" required="required">
            </div>
        </div>

        <div class="control-group">
            <label class="control-label" for="userAccountNewPassword2">New Password Again</label>
            <div class="controls">
                <input type="password" name="new_password2" id="userAccountNewPassword2" autocomplete="off" required="required">
            </div>
        </div>

        <input type="hidden" name="controller" value="<?php echo $controller; ?>">
        <input type="hidden" name="action" value="<?php echo $action . '/' . $url_params; ?>">

        <div class="control-group">
            <div class="controls">
                <button type="submit" class="btn">Save</button>
            </div>
        </div>
    </form>
</div>
