<?php use Phalcon\Tag as Tag ?>
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="Project Manager">
		<meta name="author" content="Masood Ahmed">

		<title><?php echo $AppName; ?> - <?php echo Tag::getTitle(); ?></title>

        <?php echo Tag::stylesheetLink('css/bootstrap.css'); ?>
        <?php echo Tag::stylesheetLink('css/font-awesome.css'); ?>

		<style>
            body {
                padding-top: 40px;
            }
        </style>

        <?php echo Tag::stylesheetLink('css/bootstrap-responsive.css'); ?>
        <?php echo Tag::stylesheetLink('css/bootstrap-editable.css'); ?>
        <?php echo Tag::stylesheetLink('css/jquery.easy-pie-chart.css'); ?>
        <?php echo Tag::stylesheetLink('css/style.css'); ?>

        <?php echo Tag::javascriptInclude('js/jquery-1.8.3.min.js'); ?>
        <?php echo Tag::javascriptInclude('js/bootstrap.min.js'); ?>
        <?php echo Tag::javascriptInclude('js/bootstrap-editable.min.js'); ?>
        <?php echo Tag::javascriptInclude('js/jquery.easydate-0.2.4.min.js'); ?>
        <?php echo Tag::javascriptInclude('js/jquery.easy-pie-chart.js'); ?>
	</head>

	<body <?php echo ($body_id) ? 'id="' . $body_id . '"' : ''; ?> <?php echo ($body_class) ? 'class="' . $body_class . '"' : ''; ?>>
        <header class="navbar navbar-fixed-top">
            <?php $this->partial('partials/header'); ?>
        </header>
    </body>
</html>
