<?php use Phalcon\Tag as Tag ?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Project">
        <meta name="author" content="Masood Ahmed">

        <?php echo Tag::getTitle(); ?>
        <?php echo Tag::stylesheetLink('css/bootstrap.css'); ?>

        <style>
            body {
                padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
            }
        </style>

        <?php echo Tag::stylesheetLink('css/bootstrap-responsive.css'); ?>
        <?php echo Tag::stylesheetLink('css/jdpicker.css'); ?>
        <?php echo Tag::stylesheetLink('css/style.css'); ?>

        <!--[if lt IE 9]>
			<script src="js/html5.js"></script>
		<![endif]-->
    </head>

    <body>
    	<header class="navbar navbar-inverse navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</a>
					<?php echo Tag::linkTo(array('project/index' , 'class' => 'brand', 'text' => $this->AppName)); ?>
					<div class="nav-collapse collapse">
						<?php  echo $this->menu->getNavMenu(); ?>
					</div> <!-- .nav-collapse -->
				</div> <!-- .container -->
			</div> <!-- .navbar-inner -->
		</header> <!-- .navbar -->

		<div class="container">
			<?php if ($this->flashSession->output()) { ?>
			<div class="row">
				<div class="span12">
					<?php echo $this->flashSession->output(); ?>
				</div>
			</div>
			<?php } ?>

	        <?php echo $this->getContent(); ?>
		</div> <!-- /container -->

        <hr />
        <footer class="container">
            <p>Copyright &copy; 2012 Masood Ahmed.</p>
        </footer>

        <?php if ($currentUser != null) { ?>
	        <div id="myAccountEdit" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
					<h3>Edit your account</h3>
				</div>

				<?php echo Tag::form(array('user/saveuser/' . $currentUser->id, 'class' => 'form-horizontal')); ?>
					<div class="modal-body">
						<div class="control-group">
							<label class="control-label" for="editName">Full name</label>
							<div class="controls">
								<input type="text" class="input-block-level" id="editName" placeholder="Full name" name="full_name" value="<?php echo $currentUser->full_name; ?>">
							</div>
						</div>

						<div class="control-group">
							<label class="control-label" for="editEmail">Email</label>
							<div class="controls">
								<input type="text" class="input-block-level" id="editEmail" placeholder="Email address" name="email" value="<?php echo $currentUser->email; ?>">
							</div>
						</div>

						<div class="control-group">
							<label class="control-label" for="oldPassword">Old password</label>
							<div class="controls">
								<input type="password" class="input-block-level" id="oldPassword" placeholder="Old password" name="old_password">
							</div>
						</div>

						<div class="control-group">
							<label class="control-label" for="editPassword">Password</label>
							<div class="controls">
								<input type="password" class="input-block-level" id="editPassword" placeholder="New password" name="password1">
							</div>
						</div>

						<div class="control-group">
							<label class="control-label" for="editPassword2">Re-enter password</label>
							<div class="controls">
								<input type="password" class="input-block-level" id="editPassword2" placeholder="Re-enter new password" name="password2">
							</div>
						</div>

						<input type="hidden" name="controller" value="<?php echo $this->view->getControllerName(); ?>">
						<input type="hidden" name="action" value="<?php echo $this->view->getActionName() . $extra_params; ?>">
						<input type="hidden" value="<?php echo $currentUser->id; ?>" name="id">
					</div>

					<div class="modal-footer">
						<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
						<button class="btn btn-primary">Save changes</button>
					</div>
				</form>
			</div>
		<?php } ?>

    	<?php echo Tag::javascriptInclude('js/jquery-1.8.3.min.js'); ?>
    	<?php echo Tag::javascriptInclude('js/bootstrap.min.js'); ?>
    	<?php echo Tag::javascriptInclude('js/jquery.jdpicker.js'); ?>
    </body>
</html>
